/** Created: 2026-10-04. Concrete gallery cases; technical references stay in canonical Skills. */
import type { CaseDefinition } from "./types";

type Entry = Pick<
  CaseDefinition,
  | "id"
  | "title"
  | "englishTitle"
  | "summary"
  | "primary"
  | "module"
  | "variant"
  | "capabilities"
  | "direction"
  | "rationale"
  | "why"
  | "instructions"
  | "uses"
  | "nonUses"
  | "locked"
> &
  Partial<CaseDefinition>;
const runtimeFiles: Record<string, string> = {
  d3: "data-d3.ts",
  echarts: "data-echarts.ts",
  vega: "data-vega.ts",
  visx: "data-visx.tsx",
  plot: "data-plot.ts",
  maplibre: "maps-maplibre.ts",
  deck: "maps-deck.ts",
  cesium: "maps-cesium.ts",
  leaflet: "maps-leaflet.ts",
};
const define = (entry: Entry): CaseDefinition => ({
  renderer: "SVG",
  interaction: ["state", "keyboard", "touch"],
  limitations: [
    "資料為原創示意，不代表實際統計；尚未完成跨瀏覽器與實體觸控裝置驗證。",
  ],
  fallback: "無法啟動時顯示既有海報與案例說明，明示即時範例不可用。",
  visual: {
    background: "#f5f1e8",
    foreground: "#26362f",
    accent: "#a94d30",
    font: "Arial, sans-serif",
  },
  editable: [
    "Replace synthetic content and labels with validated production data.",
    "Adjust colors, typography, dimensions, and timing while preserving readable data encoding.",
  ],
  adaptation:
    "Use one host-owned time source; wait for layout and assets before capture. Preserve semantic labels and keyboard controls. Video suitability remains unverified until seek/replay frames are tested.",
  dependencies: [],
  assets: [],
  video: "unverified",
  complexity: "medium",
  ...entry,
  module: runtimeFiles[entry.module] ?? entry.module,
});

export const dataMapCases: CaseDefinition[] = [
  define({
    id: "SA-131",
    title: "材料層級分割圖",
    englishTitle: "Material hierarchy partition",
    summary: "從整體材料到細項權重，用可切換焦點的分割圖閱讀分類關係。",
    primary: "d3",
    module: "d3",
    variant: "partition",
    capabilities: ["hierarchical-partition", "hierarchy-navigation"],
    direction: "自然材料的編輯資訊設計",
    rationale:
      "暖紙色與綠色層級讓面積、深度與材料標籤同時清楚；不使用人物或插畫裝飾。",
    why: "D3 hierarchy 與 partition 將樹狀資料轉成可自訂的矩形幾何，適合特殊階層排版。",
    instructions: "使用「切換分類」按鈕查看整體與三個分類；鍵盤可聚焦並啟動。",
    uses: ["分類資產盤點", "材料或組織階層導覽"],
    nonUses: ["需要精確比較相近數值時", "只有少量平面項目時"],
    dependencies: ["d3"],
    locked: [
      "Use d3.hierarchy().sum() followed by d3.partition().",
      "Encode hierarchy depth by rows and weight by area; preserve labels and focus navigation.",
    ],
  }),
  define({
    id: "SA-132",
    title: "保留身分的名次更新",
    englishTitle: "Keyed rank updates",
    summary: "資料排序改變時，使用穩定資料鍵維持隊伍標籤與色彩關係。",
    primary: "d3",
    module: "d3",
    variant: "ranking",
    capabilities: ["keyed-data-join", "ranking-updates"],
    direction: "清晰的運動資訊排版",
    rationale: "排行橫幅以不同色塊分辨隊伍，右側數字讓名次與數值可直接比較。",
    why: "D3 keyed join 可保留資料身分並精確管理 SVG enter、update、exit。",
    instructions: "播放會更新回合；「下一回合」可直接切換資料狀態。",
    uses: ["排行榜更新", "客製化即時資料敘事"],
    nonUses: ["只有固定資料的簡單列表", "需要現成完整儀表板控制時"],
    dependencies: ["d3"],
    interaction: ["time", "state", "keyboard", "touch"],
    visual: {
      background: "#f1f4f8",
      foreground: "#172f49",
      accent: "#b44230",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use stable team IDs as D3 data join keys.",
      "Keep labels and categorical color attached to identity as rank changes; do not simulate the chart with CSS-only bars.",
    ],
  }),
  define({
    id: "SA-133",
    title: "訊號與觀測區間",
    englishTitle: "Signal observation window",
    summary: "折線、區間與門檻線同步更新，展示多序列 option 更新。",
    primary: "echarts",
    module: "echarts",
    variant: "signal",
    capabilities: ["series-update", "uncertainty-band"],
    renderer: "Canvas 2D",
    direction: "淡色研究儀表介面",
    rationale: "綠色主訊號與低對比區間分開層級，鏽色門檻只標示需要注意的參照。",
    why: "ECharts setOption 適合保留圖表元件並更新既有命名序列。",
    instructions:
      "播放觀察資料窗更新；指向圖表可查看數值；「重設觀測窗」回到初始資料。",
    uses: ["監控訊號", "多序列營運儀表板"],
    nonUses: ["需要每個 SVG 節點獨立排版", "不能保留 Canvas 的純文件輸出"],
    dependencies: ["echarts"],
    interaction: ["time", "pointer", "state", "keyboard", "touch"],
    visual: {
      background: "#f9f7f2",
      foreground: "#173a45",
      accent: "#af6244",
      font: "Arial, sans-serif",
    },
    locked: [
      "Update named ECharts series through setOption; disable engine animation under host clock ownership.",
      "Keep the signal, lower bound, stacked range, and threshold semantically distinct.",
    ],
  }),
  define({
    id: "SA-134",
    title: "熱區與日內剖面",
    englishTitle: "Heatmap linked profile",
    summary: "點選熱區後，讀取同一天的完整剖面；同一選擇狀態連動兩種圖形。",
    primary: "echarts",
    module: "echarts",
    variant: "heatmap",
    capabilities: ["heatmap", "linked-selection"],
    renderer: "Canvas 2D",
    direction: "低眩光營運監控面板",
    rationale: "深藍灰保留低亮度背景，沙金色強調高負載，折線保留連續變化。",
    why: "ECharts 多 grid 與事件回呼適合在同一 chart instance 連接熱圖與折線。",
    instructions: "點選任一熱區，或使用「下一日」按鈕切換日內剖面。",
    uses: ["週期性運作監控", "班表與時段分布"],
    nonUses: ["只有一組少量數字", "無法提供鍵盤替代選擇的互動報表"],
    dependencies: ["echarts"],
    visual: {
      background: "#14202a",
      foreground: "#eef2ed",
      accent: "#d5b56e",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use ECharts heatmap and line series in separate grids with one selected-day state.",
      "Provide a keyboard-accessible alternative to heatmap click selection.",
    ],
  }),
  define({
    id: "SA-135",
    title: "門檻驅動散點閱讀",
    englishTitle: "Signal-driven scatter threshold",
    summary: "以 Vega signal 控制水平門檻，重新突出符合條件的樣本。",
    primary: "vega",
    module: "vega",
    variant: "threshold",
    capabilities: ["reactive-signals", "scatter-filter-emphasis"],
    direction: "科學觀測的冷色資訊圖",
    rationale:
      "保留淡化的背景樣本供比較，門檻線與符合條件的點形成清楚視覺關係。",
    why: "Vega signal 將控制值與多個 mark 的編碼連結在同一資料流。",
    instructions:
      "拖曳「門檻」滑桿或用方向鍵調整；播放時門檻在指定值附近變化。",
    uses: ["可重用規格化探索圖", "需要信號連動的資料說明"],
    nonUses: ["大量任意 DOM 介面動畫", "只有固定單值呈現"],
    dependencies: ["vega"],
    interaction: ["time", "state", "keyboard", "touch"],
    visual: {
      background: "#edf1f3",
      foreground: "#203e4d",
      accent: "#28736f",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use a Vega signal for threshold and reference it in rule and symbol encodings.",
      "Serialize view.runAsync calls and finalize the View on disposal.",
    ],
  }),
  define({
    id: "SA-136",
    title: "能源組成資料流",
    englishTitle: "Stacked composition dataflow",
    summary: "以 stack transform 形成連續組成圖，切換焦點時保留整體結構。",
    primary: "vega",
    module: "vega",
    variant: "stack",
    capabilities: ["stack-transform", "series-focus"],
    direction: "環境研究資訊設計",
    rationale:
      "藍綠到麥金的三色堆疊呈現比例變化，避免把示意能源資料包裝成真實報告。",
    why: "Vega 的 transform、facet group 與 signal 能將資料處理與互動編碼集中在可檢視規格。",
    instructions: "按「切換能源焦點」在全部與三個序列間切換。",
    uses: ["組成變化解釋", "規格化出版資訊圖"],
    nonUses: ["必須逐項精確比較的數值表", "真實能源報告而資料尚未驗證"],
    dependencies: ["vega"],
    visual: {
      background: "#edf1f3",
      foreground: "#203e4d",
      accent: "#28736f",
      font: "Arial, sans-serif",
    },
    locked: [
      "Compute stack boundaries in Vega transforms; render faceted area marks.",
      "Preserve the overall stack while focus only changes emphasis.",
    ],
  }),
  define({
    id: "SA-137",
    title: "估計值與不確定區間",
    englishTitle: "Layered interval estimates",
    summary:
      "以同一份 Vega-Lite 規格疊合區間線段與中心估計，保留可讀的不確定範圍。",
    primary: "vega-lite",
    supporting: [{ id: "vega", role: "compiled-spec-runtime" }],
    module: "vega",
    variant: "lite-interval",
    capabilities: ["layered-grammar", "interval-estimates"],
    direction: "期刊式比較圖",
    rationale: "暖白背景、細軸線與單一主色讓中心值和範圍自然分工。",
    why: "Vega-Lite layer 將兩個語意標記共用資料與尺度，再編譯為 Vega 執行。",
    instructions: "查看各列的中心點與範圍；使用「切換估計情境」更新規格資料。",
    uses: ["評估結果摘要", "研究型資訊圖"],
    nonUses: ["區間定義不明的真實統計", "複雜逐元素時間軸"],
    dependencies: ["vega-lite", "vega"],
    visual: {
      background: "#faf8f4",
      foreground: "#302e3b",
      accent: "#aa5943",
      font: "Arial, sans-serif",
    },
    locked: [
      "Compile a Vega-Lite layered rule/point specification and execute the returned Vega spec.",
      "Do not claim statistical confidence for synthetic bounds.",
    ],
  }),
  define({
    id: "SA-138",
    title: "散點樣本的二維密度",
    englishTitle: "Binned sample density",
    summary: "將 120 筆原創樣本分箱與計數，轉成可比較的二維密度方格。",
    primary: "vega-lite",
    supporting: [{ id: "vega", role: "compiled-spec-runtime" }],
    module: "vega",
    variant: "lite-density",
    capabilities: ["two-dimensional-binning", "aggregate-count"],
    direction: "礦物色的資料密度圖",
    rationale: "方格間留白顯示分箱邊界，連續橘色只編碼數量。",
    why: "Vega-Lite 將 bin 與 aggregate 直接表達為 encoding，適合可追蹤的統計轉換。",
    instructions:
      "閱讀 X/Y 分箱與樣本數色階；「切換樣本範圍」會重新計算分箱計數。",
    uses: ["分布密度摘要", "探索資料轉換"],
    nonUses: ["需要精確顯示每筆資料", "未確認分箱選擇是否合理的分析"],
    dependencies: ["vega-lite", "vega"],
    visual: {
      background: "#faf8f4",
      foreground: "#302e3b",
      accent: "#aa5943",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use genuine Vega-Lite bin transforms on both quantitative axes and aggregate count for color.",
      "Keep continuous count legend and explicit synthetic-data disclosure.",
    ],
  }),
  define({
    id: "SA-139",
    title: "環形資源閱讀器",
    englishTitle: "React radial allocation",
    summary:
      "使用 visx Pie 產生環形幾何，再以 React 狀態連結分類焦點與中央讀值。",
    primary: "visx",
    module: "visx",
    variant: "radial",
    capabilities: ["react-arc-layout", "categorical-focus"],
    direction: "暖色企業編輯版面",
    rationale:
      "環形圖和右側清單分工，中央大字對應目前分類，降低僅靠色彩識別的負擔。",
    why: "visx 提供圖形計算，讓既有 React 專案保有完整元件與互動控制。",
    instructions: "使用「下一個分類」切換圖形焦點與中央百分比。",
    uses: ["React 內嵌客製圖表", "少量分類的組成概覽"],
    nonUses: ["需精確比較非常接近的數值", "不使用 React 且只有簡單圖形"],
    dependencies: ["@visx/shape", "@visx/scale", "react", "react-dom"],
    visual: {
      background: "#f4ece1",
      foreground: "#3e332e",
      accent: "#ad5738",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use visx Pie arc layout; React owns the selected category.",
      "Keep visible text values and a keyboard-operable category control.",
    ],
  }),
  define({
    id: "SA-140",
    title: "訊號剖面精準游標",
    englishTitle: "React waveform inspection",
    summary: "曲線、區域與游標共用 visx scales，讓讀值與圖形保持座標一致。",
    primary: "visx",
    module: "visx",
    variant: "waveform",
    capabilities: ["shared-scales", "inspection-cursor"],
    direction: "醫工式訊號介面",
    rationale: "淡藍綠區域呈現整體訊號，橘色游標精確指出目前取樣。",
    why: "visx primitives 可將既有 React 狀態映射至一致 SVG 座標，避免獨立定位造成偏移。",
    instructions: "播放會移動游標；按鈕可直接切換時間取樣。",
    uses: ["時序訊號檢視", "客製化資料工具"],
    nonUses: ["真實醫療判讀", "現成圖表已足夠而不需要元件層控制"],
    dependencies: ["@visx/shape", "@visx/scale", "react", "react-dom"],
    interaction: ["time", "state", "keyboard", "touch"],
    visual: {
      background: "#e9f0f1",
      foreground: "#163a47",
      accent: "#24758a",
      font: "Arial, sans-serif",
    },
    locked: [
      "Share visx x/y scales across LinePath, AreaClosed, cursor, and numeric readout.",
      "Use the host clock for cursor sampling; unmount the React root on disposal.",
    ],
  }),
  define({
    id: "SA-141",
    title: "分布與累積頻率",
    englishTitle: "Distribution and cumulative count",
    summary: "同一批樣本使用 Plot binX 轉成直方圖，再切換累積計數觀點。",
    primary: "observable-plot",
    module: "plot",
    variant: "histogram",
    capabilities: ["bin-transform", "cumulative-distribution"],
    direction: "柔紫統計資訊設計",
    rationale: "單一柱色與固定參照線讓讀者專注在分布形狀與轉換差異。",
    why: "Observable Plot 的轉換與 mark 可以用簡短、語意清楚的規格組合統計圖。",
    instructions: "按「切換累積分布」比較一般頻率與累積頻率。",
    uses: ["探索分析摘要", "資料轉換教學"],
    nonUses: ["複雜應用級圖表狀態機", "沒有說明分箱策略的真實結論"],
    dependencies: ["@observablehq/plot"],
    visual: {
      background: "#f0f0f7",
      foreground: "#3a3e60",
      accent: "#6963a1",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use Plot.binX and Plot.rectY for frequency/cumulative modes.",
      "Retain common x-domain while updating the y-axis meaning.",
    ],
  }),
  define({
    id: "SA-142",
    title: "四季同尺度分面",
    englishTitle: "Seasonal small multiples",
    summary: "將四組季節資料分面排列，使用一致尺度比較波動與觀測窗。",
    primary: "observable-plot",
    module: "plot",
    variant: "facets",
    capabilities: ["small-multiples", "faceted-marks"],
    direction: "季節研究的紙本資訊圖",
    rationale: "四個小圖分享尺度與細線網格，用有限的自然色區分季節。",
    why: "Plot 的 facet channel 讓相同 mark 自動分配至子圖，減少手工重複佈局。",
    instructions: "使用「切換觀測窗」比較完整月份與前 20 日。",
    uses: ["組間時間序列比較", "編輯式資料敘事"],
    nonUses: ["每個子圖尺度不同卻要比較高度", "只有一組單值資料"],
    dependencies: ["@observablehq/plot"],
    visual: {
      background: "#fffaf1",
      foreground: "#263d42",
      accent: "#ac613f",
      font: "Arial, sans-serif",
    },
    locked: [
      "Use Plot fy facets with fixed shared y-domain and line/dot marks.",
      "Apply the observation-window filter consistently to every visible mark.",
    ],
  }),
  define({
    id: "SA-143",
    title: "沿線地理鏡頭",
    englishTitle: "Local route camera story",
    summary:
      "以本機 GeoJSON 路線驅動 MapLibre 地理鏡頭，讓路徑與位置具空間連續性。",
    primary: "maplibre",
    module: "maplibre",
    variant: "route",
    capabilities: ["geographic-camera", "geojson-route"],
    renderer: "WebGL",
    interaction: ["time", "pointer", "state", "keyboard", "touch"],
    direction: "輕量戶外製圖",
    rationale: "淡草色分區與鏽紅路線強調地理連續性；不依賴底圖照片。",
    why: "MapLibre 提供投影、地理鏡頭和向量圖層，適合真正需要經緯度與鏡頭的故事。",
    instructions:
      "播放沿線移動，拖曳後交由手動鏡頭；按「下一個地點」或「重設鏡頭」。",
    uses: ["位置敘事", "地理路徑展示"],
    nonUses: ["真實導航", "只有抽象流程圖"],
    dependencies: ["maplibre-gl"],
    complexity: "high",
    visual: {
      background: "#edf1e4",
      foreground: "#314232",
      accent: "#a65838",
      font: "Arial, sans-serif",
    },
    limitations: [
      "所有路線與分區為原創地理示意，不是真實街道或行政區。",
      "未使用圖磚、字型服務或地形；WebGL 與 worker 支援需逐環境驗證。",
    ],
    locked: [
      "Use MapLibre GL JS with local GeoJSON [longitude, latitude] coordinates.",
      "Move the camera through host-driven jumpTo; user interaction explicitly takes ownership.",
      "Do not add unlicensed tiles or silently replace the local schematic fixture.",
    ],
  }),
  define({
    id: "SA-144",
    title: "向量分區互動選取",
    englishTitle: "Vector district selection",
    summary:
      "用 MapLibre feature-state 選取本機分區，將地理圖形與資料讀值連動。",
    primary: "maplibre",
    module: "maplibre",
    variant: "districts",
    capabilities: ["feature-state", "choropleth-selection"],
    renderer: "WebGL",
    direction: "公共資訊製圖",
    rationale:
      "連續綠色編碼權重，白色界線分離原創示意區域，選取狀態加強視覺對應。",
    why: "Feature state 可更新選取而不必重傳整份 GeoJSON。",
    instructions: "點選任一分區或按「下一個分區」；可拖曳地圖。",
    uses: ["地理資料選取", "向量圖層導覽"],
    nonUses: ["真實政策或區域決策", "沒有地理座標需求的矩形編輯器"],
    dependencies: ["maplibre-gl"],
    complexity: "high",
    visual: {
      background: "#f0efe7",
      foreground: "#253c3b",
      accent: "#996143",
      font: "Arial, sans-serif",
    },
    limitations: [
      "原創示意分區不是實際行政邊界，權重不代表統計資料。",
      "無底圖服務；跨裝置 WebGL 支援尚未驗證。",
    ],
    locked: [
      "Keep stable GeoJSON feature IDs and use setFeatureState for selection.",
      "Provide a keyboard selection button equivalent to pointer selection.",
    ],
  }),
  define({
    id: "SA-145",
    title: "四千個位置的 GPU 圖層",
    englishTitle: "GPU observation field",
    summary:
      "4,096 筆原創位置以 deck.gl attribute layer 顯示，可切換高值篩選。",
    primary: "deckgl",
    module: "deck",
    variant: "points",
    capabilities: ["gpu-point-layer", "attribute-update"],
    renderer: "WebGL",
    direction: "地理觀測的淡色密度場",
    rationale:
      "淡石色背景保留各觀測點的分布與權重差異；不使用發光粒子造成資料歧義。",
    why: "deck.gl layer 將大量地理物件映射為 GPU attributes，適合資料量較多的地理覆蓋圖。",
    instructions:
      "指向位置查看權重；按「切換高值篩選」隱藏低值位置；可拖曳視野。",
    uses: ["點位密度探索", "地理資料覆蓋圖"],
    nonUses: ["以此案例推論效能極限", "少量標記的基本地圖"],
    dependencies: ["@deck.gl/core", "@deck.gl/layers"],
    complexity: "high",
    visual: {
      background: "#f1eee8",
      foreground: "#2d454a",
      accent: "#a75c48",
      font: "Arial, sans-serif",
    },
    limitations: [
      "4,096 筆是示意資料量，不是測得效能上限。",
      "未使用底圖；GPU 記憶體與觸控效能尚未量測。",
    ],
    locked: [
      "Render original coordinate data with deck.gl ScatterplotLayer and explicit radius update triggers.",
      "Preserve data-count disclosure and avoid invented performance claims.",
    ],
  }),
  define({
    id: "SA-146",
    title: "時間軌跡地理圖層",
    englishTitle: "Time-indexed geographic trails",
    summary:
      "36 條原創路徑以 TripsLayer 依時間顯示尾跡，讓地理移動與時間連動。",
    primary: "deckgl",
    module: "deck",
    variant: "trips",
    capabilities: ["timestamped-trails", "geographic-temporal-layer"],
    renderer: "WebGL",
    interaction: ["time", "pointer", "state", "keyboard", "touch"],
    direction: "交通研究的低亮度視圖",
    rationale: "青綠與沙金路徑在深色底上區分群組，低對比完整路網保留上下文。",
    why: "TripsLayer 直接處理路徑 timestamps、currentTime 與 trailLength，避免自行維護大量 DOM。",
    instructions: "播放觀察尾跡流動；拖曳改變視野；按「重播軌跡」回到起點。",
    uses: ["移動軌跡敘事", "時間索引地理資料"],
    nonUses: ["真實交通分析而未驗證資料", "少量簡單路線只需靜態圖"],
    dependencies: ["@deck.gl/core", "@deck.gl/layers", "@deck.gl/geo-layers"],
    complexity: "high",
    visual: {
      background: "#122d35",
      foreground: "#e2efe9",
      accent: "#b5c66f",
      font: "Arial, sans-serif",
    },
    limitations: [
      "全部路徑為原創合成資料，不代表實際交通。",
      "Timestamp 精度、視野與影片回放仍需針對正式資料驗證。",
    ],
    locked: [
      "Use genuine TripsLayer timestamps and host-controlled currentTime.",
      "Maintain static path context and a bounded trailLength.",
    ],
  }),
  define({
    id: "SA-147",
    title: "地球曲面的跨域航線",
    englishTitle: "Ellipsoid route perspective",
    summary: "在真正 WGS84 橢球體上顯示抬升路徑，展示地球尺度與三維相機關係。",
    primary: "cesiumjs",
    module: "cesium",
    variant: "globe",
    capabilities: ["ellipsoid-globe", "geographic-camera"],
    renderer: "WebGL",
    interaction: ["time", "pointer", "state", "keyboard", "touch"],
    direction: "地球科學展示",
    rationale:
      "經緯格線清楚呈現曲面，金色與青色路線表達不同連結，不冒充衛星影像。",
    why: "Cesium 適合橢球地球、地理座標高度與大尺度相機；一般 2D 地圖不足以表達此空間關係。",
    instructions:
      "播放觀察鏡頭變化；拖曳後手動操作；按「切換視角」或「重設相機」。",
    uses: ["地球尺度空間說明", "地理座標的高度敘事"],
    nonUses: ["真實航線規劃", "需要真實地形而尚無地形來源"],
    dependencies: ["cesium"],
    complexity: "high",
    visual: {
      background: "#101c2d",
      foreground: "#e7eef0",
      accent: "#d5b675",
      font: "Arial, sans-serif",
    },
    limitations: [
      "使用 EllipsoidTerrainProvider，沒有載入真實地形或衛星影像。",
      "路徑為原創示意，並非導航解或地理最短路徑。",
      "需以既有準備腳本部署本機 Cesium Workers、Assets、Widgets、ThirdParty 目錄。",
    ],
    locked: [
      "Use Cesium WGS84 ellipsoid and geodetic altitude positions.",
      "Disable the default render loop and drive JulianDate/render from host time.",
      "Use local GridImageryProvider only; do not imply terrain or satellite imagery.",
    ],
  }),
  define({
    id: "SA-148",
    title: "地理座標立體資料",
    englishTitle: "Geodetic data columns",
    summary: "在橢球基準面配置 30 個資料立柱，以高度與鏡頭方位呈現空間關係。",
    primary: "cesiumjs",
    module: "cesium",
    variant: "columns",
    capabilities: ["geodetic-geometry", "orbit-camera"],
    renderer: "WebGL",
    interaction: ["time", "pointer", "state", "keyboard", "touch"],
    direction: "建築尺度的資料模型",
    rationale:
      "淡灰綠基底和有限土色立柱呈現幾何高度，避免把合成資料看成真實建築。",
    why: "Cesium entities 將地理位置、高度與三維幾何綁定，適合需要地球基準的空間資料。",
    instructions: "播放查看環繞鏡頭；按「切換視角」改變方位；可手動拖曳。",
    uses: ["地理數值立體呈現", "空間尺度教學"],
    nonUses: ["真實建築陰影或地形分析", "沒有地理需求的產品 3D"],
    dependencies: ["cesium"],
    complexity: "high",
    visual: {
      background: "#e7e9e6",
      foreground: "#29423f",
      accent: "#8e5c39",
      font: "Arial, sans-serif",
    },
    limitations: [
      "立柱是原創合成資料，不是真實建築。",
      "僅橢球基準面，沒有高程資料、影像或地形。",
      "需以既有準備腳本部署本機 Cesium Workers、Assets、Widgets、ThirdParty 目錄。",
      "正式影片需等待 geometry 與影像格線載入後驗證 seek/replay。",
    ],
    locked: [
      "Position actual Cesium box entities with longitude/latitude and altitude in meters.",
      "Use a host-controlled HeadingPitchRange camera with explicit interaction handoff.",
    ],
  }),
  define({
    id: "SA-149",
    title: "可逐站閱讀的散步地圖",
    englishTitle: "Waypoint map reader",
    summary: "Leaflet 路線與圓形標記連結站點文字，可點選或逐站切換。",
    primary: "leaflet",
    module: "leaflet",
    variant: "waypoints",
    capabilities: ["waypoint-navigation", "map-marker-selection"],
    renderer: "SVG",
    direction: "紙本散步指南",
    rationale: "奶油紙色與虛線路徑使站點順序清楚，圓形標記不依賴額外圖示資產。",
    why: "Leaflet 適合輕量二維地圖圖層與標記互動，無須引入 3D 引擎。",
    instructions: "點選圓形標記或按「下一站」；使用「縮放視野」切換比例。",
    uses: ["展場位置導覽", "少量站點的二維路線"],
    nonUses: ["真實導航", "3D 地形與大規模 GPU 圖層"],
    dependencies: ["leaflet"],
    visual: {
      background: "#fff8e7",
      foreground: "#463f30",
      accent: "#a05839",
      font: "Arial, sans-serif",
    },
    limitations: [
      "所有站點與路徑為原創地理示意，不是真實散步建議。",
      "沒有底圖或真實街道資料；觸控裝置尚未實測。",
    ],
    locked: [
      "Use Leaflet polylines and circle markers; convert GeoJSON lon/lat to Leaflet lat/lng explicitly.",
      "Keep point selection accessible through a sequential button.",
    ],
  }),
  define({
    id: "SA-150",
    title: "區域圖層條件篩選",
    englishTitle: "GeoJSON region filtering",
    summary: "以 Leaflet GeoJSON 圖層呈現區域，使用資料條件淡化低值範圍。",
    primary: "leaflet",
    module: "leaflet",
    variant: "regions",
    capabilities: ["geojson-region-layer", "conditional-emphasis"],
    renderer: "SVG",
    direction: "平面區域資訊圖",
    rationale: "兩段綠色提供權重差異，淡化機制保留被篩選區域的空間上下文。",
    why: "Leaflet 的 GeoJSON layer 與 setStyle 足以完成少量區域的互動篩選，整合成本低於 GPU 地圖場景。",
    instructions: "按「切換高值區域」改變篩選；點選區域查看權重。",
    uses: ["少量區域資料探索", "二維地理互動"],
    nonUses: ["真實行政決策", "需要向量圖磚或立體鏡頭"],
    dependencies: ["leaflet"],
    visual: {
      background: "#eaf0ee",
      foreground: "#264b49",
      accent: "#347d7b",
      font: "Arial, sans-serif",
    },
    limitations: [
      "分區是原創示意形狀，不是實際行政邊界。",
      "沒有外部圖磚；尚未驗證大量 GeoJSON 的效能。",
    ],
    locked: [
      "Use actual Leaflet GeoJSON layers and setStyle updates.",
      "Keep filtered geometry visible at low opacity to retain geographic context.",
    ],
  }),
];
