/** Created: 2026-10-04. Concrete showcase metadata; reusable guidance lives in technology references. */
import type { CaseDefinition } from "./types";

type Seed = Omit<
  CaseDefinition,
  "assets" | "editable" | "adaptation" | "complexity" | "visual"
> &
  Partial<
    Pick<
      CaseDefinition,
      "assets" | "editable" | "adaptation" | "complexity" | "visual"
    >
  >;
function define(seed: Seed): CaseDefinition {
  return {
    assets: [],
    complexity: "medium",
    durationSeconds: 8,
    visual: {
      background: "#f0eee2",
      foreground: "#253c3d",
      accent: "#bd764d",
      font: "Arial, sans-serif",
    },
    editable: [
      "Replace labels and content without changing capability ownership.",
      "Choose case-specific colors, composition, density, dimensions and timing; do not inherit legacy illustration styling.",
    ],
    adaptation:
      "Keep one external time source. Mount only when opened; suspend offscreen and in hidden tabs. Use a static representative frame for reduced motion. Dispose all owned resources. Verify target browsers, keyboard and touch. A browser preview is not proof of deterministic video export.",
    ...seed,
    module: /\.tsx?$/.test(seed.module)
      ? seed.module
      : seed.module + (seed.module === "scene-r3f" ? ".tsx" : ".ts"),
  };
}
export const gpuSceneCases: CaseDefinition[] = [
  define({
    id: "SA-161",
    title: "精密音響・分層拆解",
    englishTitle: "Acoustic Module Exploded View",
    summary: "從完整產品旋轉到五層構造分離，讓材質與零件關係清楚可讀。",
    primary: "threejs",
    capabilities: ["product-3d", "exploded-view"],
    module: "scene-three",
    variant: "product",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "暖白產品攝影",
    rationale: "柔和底色、金屬環與苔綠外殼凸顯實際深度及零件間距。",
    why: "Three.js 的 3D 幾何、透視相機與標準材質能表現轉向後仍成立的構造。",
    uses: ["產品結構展示", "組裝步驟說明"],
    nonUses: ["只需單張產品圖片", "沒有立體需求的介面轉場"],
    instructions: "播放或拖曳時間軸，檢視拆解與收合狀態。",
    limitations: ["程序式示意模型，並非工程 CAD", "GPU 與目標瀏覽器必須實測"],
    fallback: "使用已生成的代表性海報。",
    locked: [
      "Use real Three.js meshes and perspective projection.",
      "Preserve the complete-to-exploded relationship and host-driven time.",
      "Dispose shared geometry, materials, renderer and WebGL context.",
    ],
    dependencies: ["three"],
    video: "frame-driven",
  }),
  define({
    id: "SA-162",
    title: "科學波場・600 柱實例",
    englishTitle: "Instanced Wave Lattice",
    summary: "以一份幾何與 600 組矩陣呈現連續波面，展示實例化更新。",
    primary: "threejs",
    capabilities: ["instancing", "procedural-geometry"],
    module: "scene-three",
    variant: "lattice",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "科學模型與青綠格網",
    rationale: "規律網格與高度差讓波的傳遞方向、實例密度與透視關係可辨識。",
    why: "InstancedMesh 讓重複幾何透過矩陣及逐實例色彩更新，無須建立 600 份 Mesh。",
    uses: ["程序式資料地形", "重複零件動態展示"],
    nonUses: ["精確讀值的無障礙圖表", "只有數個 DOM 元素的動畫"],
    instructions: "拖曳時間軸觀察兩個方向的波相疊。",
    limitations: ["高度為合成波函數，不是觀測資料", "未主張優於其他實作的效能"],
    fallback: "以靜態截圖呈現波面。",
    locked: [
      "Use 600 InstancedMesh transforms with shared geometry.",
      "Compute height from absolute time, not accumulated delta.",
      "Keep device pixel ratio bounded.",
    ],
    dependencies: ["three"],
    video: "frame-driven",
    visual: {
      background: "#092932",
      foreground: "#e4f3e7",
      accent: "#7aa893",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-163",
    title: "模組家具・材質配置",
    englishTitle: "React Furniture Configurator",
    summary: "用可鍵盤操作的色票切換 3D 座椅材質，同時維持穩定的場景生命週期。",
    primary: "r3f",
    supporting: [
      { id: "threejs", role: "3D renderer" },
      { id: "drei", role: "RoundedBox geometry and Line seam helpers" },
    ],
    capabilities: ["react-scene-state", "material-configuration"],
    module: "scene-r3f",
    variant: "configurator",
    renderer: "WebGL",
    interaction: ["state", "pointer", "keyboard", "touch"],
    direction: "日光家具型錄",
    rationale: "低彩度布料、木腳與留白讓配置操作聚焦於材質改變。",
    why: "React Three Fiber 管理宣告式場景，Drei 提供圓角幾何；材質狀態與播放時鐘有明確邊界。",
    uses: ["React 商品配置介面", "既有 React 專案中的 3D 狀態展示"],
    nonUses: ["無 React 的小型網頁", "只有平面色票的商品圖"],
    instructions: "點選苔綠、陶土或深藍；可用 Tab 與 Enter 操作色票。",
    limitations: ["原創程序式材質，非量測掃描材質", "配置狀態未寫入永久儲存"],
    fallback: "顯示靜態產品圖與文字色票。",
    locked: [
      "Use R3F with frameloop never and explicit advance.",
      "Use Drei RoundedBox for actual geometry.",
      "Keep color buttons keyboard accessible and destroy the React scene root.",
    ],
    dependencies: ["react", "three", "@react-three/fiber", "@react-three/drei"],
    video: "adapter-required",
  }),
  define({
    id: "SA-164",
    title: "軌道構圖・空間線條",
    englishTitle: "Orbital Scene Components",
    summary: "三組世界座標軌道與衛星構成可尋址的 React 場景組件。",
    primary: "r3f",
    supporting: [
      { id: "threejs", role: "3D renderer" },
      { id: "drei", role: "World-space Line helper" },
    ],
    capabilities: ["scene-composition", "world-space-lines"],
    module: "scene-r3f",
    variant: "orbits",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "淺色天體模型",
    rationale: "三種克制配色區分軌道，以實際遮擋提供空間判讀。",
    why: "場景組件與 Drei Line 可協同管理不同軌道，線寬維持清楚可辨。",
    uses: ["空間系統示意", "React 3D 解說組件"],
    nonUses: ["具有科學精度要求的天體模擬", "單一 SVG 即可說明的平面圖"],
    instructions: "拖曳時間軸檢視衛星在前後空間的位置。",
    limitations: ["軌道是示意函數，不是物理軌道計算", "未使用外部星體材質"],
    fallback: "以標註軌道的靜態圖代替動畫。",
    locked: [
      "Construct genuine world-space line geometry through Drei.",
      "Animate satellites from absolute host time.",
      "Unmount the R3F root and release its WebGL renderer.",
    ],
    dependencies: ["react", "three", "@react-three/fiber", "@react-three/drei"],
    video: "frame-driven",
  }),
  define({
    id: "SA-165",
    title: "空間樂譜・鏡頭編排",
    englishTitle: "Authored Spatial Camera Score",
    summary:
      "三條已編排的 Theatre.js 曲線控制方位、高度與注視點，產生有停留節奏的建築巡覽。",
    primary: "theatrejs",
    supporting: [{ id: "threejs", role: "Scene renderer" }],
    capabilities: ["authored-keyframes", "camera-choreography"],
    module: "scene-theatre",
    variant: "camera",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "建築量體研究",
    rationale: "中性的格線與量體讓相機位置改變成為主角，避免特效掩蓋鏡頭節奏。",
    why: "Theatre.js 讀取實際 BasicKeyframedTrack，將多參數插值集中在同一條 sequence。",
    uses: ["需反覆調整節點節奏的鏡頭", "多人協作前的參數編排"],
    nonUses: ["固定等速旋轉", "即時自由相機操作"],
    instructions: "播放或定位 2 秒、4.5 秒、6 秒，觀察不同鏡位與停留節奏。",
    limitations: [
      "狀態以程式手工編排，未宣稱由 Studio 匯出",
      "結構對應已安裝的 Theatre.js 0.7.2，升級須驗證",
    ],
    fallback: "使用代表性鏡位海報。",
    locked: [
      "Load real Theatre BasicKeyframedTrack data for azimuth, height and focus.",
      "Set sequence.position from host time; never play a second clock.",
      "Keep the authored project state and its version contract explicit.",
    ],
    dependencies: ["@theatre/core", "three"],
    video: "frame-driven",
    complexity: "high",
  }),
  define({
    id: "SA-166",
    title: "環形組件・多軌收合",
    englishTitle: "Authored Assembly Sequence",
    summary:
      "以關鍵影格同步拆解距離、旋轉與升降，形成停留、展示、收合的完整段落。",
    primary: "theatrejs",
    supporting: [{ id: "threejs", role: "Scene renderer" }],
    capabilities: ["authored-keyframes", "multi-parameter-sequencing"],
    module: "scene-theatre",
    variant: "assembly",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "工業珠寶展示",
    rationale: "金屬色與深綠背景讓環形層次清楚，拆解停留用於閱讀構造。",
    why: "三條不同節點分布的 Theatre.js 軌道控制同一組件，表現時間設計而非單純正弦循環。",
    uses: ["組件發表動畫", "需要美術可調關鍵點的多參數表演"],
    nonUses: ["只有一個透明度轉場", "要求真實機械公差的工程模擬"],
    instructions: "比較 0 秒、3 秒、5 秒與 8 秒的拆解和停留。",
    limitations: [
      "程序式環形模型",
      "編排狀態為程式手工建立，非虛構的 Studio 檔案",
    ],
    fallback: "顯示拆解狀態的海報。",
    locked: [
      "Keep independent authored spread, turn and lift tracks.",
      "Use actual Theatre interpolation and a single externally sought sequence.",
      "Detach the sheet object and dispose Three resources.",
    ],
    dependencies: ["@theatre/core", "three"],
    video: "frame-driven",
    complexity: "high",
    visual: {
      background: "#18383d",
      foreground: "#e5e4c7",
      accent: "#d6a959",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-167",
    title: "材質庫・空間拾取",
    englishTitle: "Babylon Material Picking",
    summary: "在五個立體樣本中拾取物件，選中的樣本升起並改變發光狀態。",
    primary: "babylonjs",
    capabilities: ["scene-picking", "material-state"],
    module: "scene-babylon",
    variant: "picking",
    renderer: "WebGL",
    interaction: ["pointer", "touch", "keyboard", "state"],
    direction: "設計材料展示桌",
    rationale: "淺綠場景與陶土、藍綠材質讓選取回饋不依賴強烈霓虹效果。",
    why: "Babylon.js 的場景拾取、材質與相機由同一引擎管理，適合互動 3D 選擇流程。",
    uses: ["3D 樣品選擇器", "場景物件互動展示"],
    nonUses: ["單純平面按鈕列", "需讀屏逐項說明但未建立 DOM 對照的複雜物件庫"],
    instructions: "點選物件，或聚焦畫布後用左右方向鍵選取。",
    limitations: ["只有五個程序式樣本", "外部讀屏描述仍須依正式產品內容補足"],
    fallback: "以五項文字與靜態圖清單呈現。",
    locked: [
      "Use Babylon scene.pick for pointer interaction.",
      "Provide keyboard selection without camera-control conflicts.",
      "Render manually and dispose scene plus engine.",
    ],
    dependencies: ["@babylonjs/core"],
    video: "adapter-required",
  }),
  define({
    id: "SA-168",
    title: "城市訊號・900 個薄實例",
    englishTitle: "Babylon Thin Instance City",
    summary: "以薄實例矩陣更新 900 個量體，讓徑向訊號穿越城市格網。",
    primary: "babylonjs",
    capabilities: ["thin-instances", "matrix-buffer-updates"],
    module: "scene-babylon",
    variant: "city",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "暖紙建築模型",
    rationale: "克制的紙板模型色與建築陰影便於觀察高度傳播。",
    why: "Babylon thin instances 用矩陣緩衝區描述同一幾何的重複配置。",
    uses: ["大量重複物件場景", "程序式空間訊號展示"],
    nonUses: ["少數物件的場景", "具有獨立複雜互動狀態的每棟建築"],
    instructions: "播放或定位不同時間，觀察同心波推動的量體高度。",
    limitations: [
      "合成格網，並非真實城市或地理資料",
      "未與其他引擎進行效能比較",
    ],
    fallback: "使用固定波相的鳥瞰圖。",
    locked: [
      "Use thinInstanceSetBuffer and update the actual matrix buffer.",
      "Refresh bounds after scaling updates.",
      "Do not replace the scene with 900 independent engine nodes.",
    ],
    dependencies: ["@babylonjs/core"],
    video: "frame-driven",
    complexity: "high",
  }),
  define({
    id: "SA-169",
    title: "軌道字形・720 個精靈",
    englishTitle: "Pixi Sprite Orbit Field",
    summary: "單一程序式材質形成六圈動態精靈場，展示大量 2D 物件的獨立變換。",
    primary: "pixijs",
    capabilities: ["sprite-field", "texture-reuse"],
    module: "gpu-pixi",
    variant: "sprites",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "編輯設計與軌道圖形",
    rationale: "扁平字形般的短筆畫，在環形配置中顯示密度與切線方向。",
    why: "PixiJS 使用同一份生成材質建立 Sprite，適合大量 2D 變換與 GPU 批次繪製。",
    uses: ["大量 2D 符號動態", "品牌識別圖形場"],
    nonUses: ["少數 HTML 文字", "需文字選取或語意標記的內容"],
    instructions: "播放或拖曳時間軸觀察各圈的速度差。",
    limitations: [
      "程序式短筆畫不是字型排版",
      "720 是本案例的物件數，並非通用安全上限",
    ],
    fallback: "顯示靜態軌道海報。",
    locked: [
      "Generate one actual Pixi texture and reuse it for 720 sprites.",
      "Use private stopped ticker and explicit app.render.",
      "Destroy the texture and application on teardown.",
    ],
    dependencies: ["pixi.js"],
    video: "frame-driven",
    visual: {
      background: "#211d33",
      foreground: "#f9efcc",
      accent: "#efbd70",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-170",
    title: "柔與銳・即時遮罩透鏡",
    englishTitle: "Pixi Filter Mask Lens",
    summary: "以可移動的清晰視窗揭露模糊色塊，展示容器濾鏡與幾何遮罩。",
    primary: "pixijs",
    capabilities: ["gpu-filter", "container-mask"],
    module: "gpu-pixi",
    variant: "mask",
    renderer: "WebGL",
    interaction: ["pointer", "touch", "keyboard", "timeline"],
    direction: "陶土色抽象平面",
    rationale: "柔邊背景與硬邊視窗形成容易辨識的同內容比較。",
    why: "Pixi 容器可分別管理濾鏡與遮罩，讓同一組幾何在不同合成分支呈現。",
    uses: ["內容揭露效果", "GPU 圖像合成探索"],
    nonUses: ["可由單一 CSS blur 達成的靜態模糊", "沒有遮罩需求的簡單圖卡"],
    instructions:
      "移動指標、觸碰或用左右方向鍵控制清晰視窗；未操作時會自動掃描。",
    limitations: [
      "高模糊品質需要額外 GPU 工作",
      "互動視窗狀態需固定後才可確定性輸出",
    ],
    fallback: "顯示柔銳並列的固定代表畫面。",
    locked: [
      "Use a real Pixi BlurFilter and Graphics mask.",
      "Keep one mask owner and stop the private ticker.",
      "Dispose filters and both container branches.",
    ],
    dependencies: ["pixi.js"],
    video: "adapter-required",
    visual: {
      background: "#f2c6a9",
      foreground: "#2b2735",
      accent: "#f65d47",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-171",
    title: "雙源干涉・片段波場",
    englishTitle: "GLSL Wave Interference",
    summary: "兩個波源在片段著色器中即時計算相位疊加，形成可尋址的干涉紋。",
    primary: "regl",
    supporting: [{ id: "glsl", role: "Fragment shader technique" }],
    capabilities: ["fragment-shader", "wave-interference"],
    module: "gpu-regl",
    variant: "interference",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "科學資訊圖像",
    rationale: "綠白對比與橘色波源使節線與兩個中心的位置清楚可見。",
    why: "regl 將 GPU draw command、uniform 與全畫面三角形集中，GLSL 直接計算每個像素。",
    uses: ["程序式波形影像", "著色器概念教學"],
    nonUses: ["要讓每個波節成為 DOM 元素", "需要數值精度驗證的物理求解"],
    instructions: "拖曳時間軸比較相位移動與固定的波源位置。",
    limitations: [
      "視覺模型，不是精密聲學模擬",
      "Shader 浮點結果可能隨 GPU 略有差異",
    ],
    fallback: "使用波場海報。",
    locked: [
      "Use a real fragment shader through regl.",
      "Provide absolute time as a uniform.",
      "Compile once per mount and destroy regl on close.",
    ],
    dependencies: ["regl"],
    video: "frame-driven",
  }),
  define({
    id: "SA-172",
    title: "色帶流場・域扭曲",
    englishTitle: "GLSL Domain-Warped Color Field",
    summary: "片段著色器反覆扭曲座標，讓色帶形成流動、摺疊的抽象紋理。",
    primary: "regl",
    supporting: [{ id: "glsl", role: "Domain-warping shader technique" }],
    capabilities: ["domain-warping", "procedural-texture"],
    module: "gpu-regl",
    variant: "flow",
    renderer: "WebGL",
    interaction: ["timeline"],
    direction: "暖色實驗海報",
    rationale: "杏色、陶土與紫灰提供可讀的流向，並避免預設霓虹外觀。",
    why: "程序式紋理直接由 GLSL 座標運算產生，不需載入貼圖或逐像素 CPU 更新。",
    uses: ["原創程序式背景", "著色器動態視覺"],
    nonUses: ["文字與資料的主要資訊層", "只需固定漸層的介面"],
    instructions: "播放觀看色帶變形，或固定任意時間作為生成式構圖。",
    limitations: ["未提供跨 GPU 像素完全相同的保證", "本案例沒有外部紋理"],
    fallback: "使用選定時間的靜態影像。",
    locked: [
      "Preserve actual shader domain warping and one time uniform.",
      "Do not approximate with CSS gradients.",
      "Keep bounded resolution and release WebGL resources.",
    ],
    dependencies: ["regl"],
    video: "frame-driven",
    visual: {
      background: "#282142",
      foreground: "#ffeddb",
      accent: "#f27845",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-173",
    title: "重力分流・碰撞料槽",
    englishTitle: "Matter Gravity Sorting",
    summary: "35 個剛體沿斜坡碰撞落下，可施力擾動並在回跳時重建模擬。",
    primary: "matterjs",
    capabilities: ["rigid-body-collision", "fixed-step-simulation"],
    module: "physics-matter",
    variant: "collision",
    renderer: "Canvas 2D",
    interaction: ["pointer", "keyboard", "touch", "timeline"],
    direction: "實驗器材圖解",
    rationale: "米色底、深色料槽與四色剛體讓碰撞過程清楚可讀。",
    why: "Matter.js 提供碰撞、摩擦與回彈；Canvas 僅負責描繪真實模擬狀態。",
    uses: ["互動剛體玩具", "可重播的物理運動草圖"],
    nonUses: ["必須命中精確時間點的介面彈簧", "工程級物理準確度需求"],
    instructions: "點選畫布或按空白鍵施力；拖曳回較早時間會重建初始狀態。",
    limitations: [
      "互動輸入未記錄為可匯出的事件軌",
      "固定步長不等於所有瀏覽器逐位元相同",
    ],
    fallback: "使用固定模擬步數的靜態畫面。",
    locked: [
      "Use real Matter.Engine updates at 1000 / 60 ms.",
      "Rebuild bodies and engine state when seeking backward.",
      "Do not run Matter.Runner or a second clock.",
    ],
    dependencies: ["matter-js"],
    video: "adapter-required",
    complexity: "high",
  }),
  define({
    id: "SA-174",
    title: "張力研究・懸吊約束",
    englishTitle: "Matter Constraint Pendulums",
    summary: "七組不同長度的擺錘由 Constraint 連接錨點，展現相位逐漸分離。",
    primary: "matterjs",
    capabilities: ["constraints", "pendulum-simulation"],
    module: "physics-matter",
    variant: "constraints",
    renderer: "Canvas 2D",
    interaction: ["pointer", "keyboard", "touch", "timeline"],
    direction: "理科實驗室圖版",
    rationale: "細懸索與實心擺錘讓約束位置和長度直接可見。",
    why: "Matter Constraint 處理繫點與剛體之間的限制，適合展示真實相互作用而非預設路徑。",
    uses: ["連桿與懸吊概念展示", "物理互動實驗"],
    nonUses: ["只有視覺搖擺的裝飾", "高精度機械分析"],
    instructions: "播放觀察不同長度的相位差；點選或空白鍵可施加額外力量。",
    limitations: [
      "未記錄互動事件，錄影適配需要固定或重播輸入",
      "沒有工程數值驗證",
    ],
    fallback: "顯示具約束線條的靜態圖。",
    locked: [
      "Create actual Matter constraints and bodies.",
      "Use fixed timesteps and reset on backward seek.",
      "Clear constraints, world, events and engine on close.",
    ],
    dependencies: ["matter-js"],
    video: "adapter-required",
  }),
  define({
    id: "SA-175",
    title: "連線場・指標排斥",
    englishTitle: "tsParticles Connected Field",
    summary: "90 個粒子以鄰近連線形成網絡，指標或方向鍵移動排斥中心。",
    primary: "tsparticles",
    capabilities: ["particle-links", "pointer-field"],
    module: "physics-particles",
    variant: "network",
    renderer: "Canvas 2D",
    interaction: ["pointer", "touch", "keyboard", "timeline"],
    direction: "克制的網絡資訊視覺",
    rationale: "低亮度青藍底與淺色線點提供網絡密度辨識。",
    why: "tsParticles slim 提供粒子形狀與 links 互動插件；本案例以明確的時間適配器控制位置及繪製。",
    uses: ["可互動的連線背景", "有限粒子網絡效果"],
    nonUses: ["需要精確語意關係的節點圖", "大量真實網絡資料分析"],
    instructions: "移動指標，或聚焦畫布後使用方向鍵移動排斥中心。",
    limitations: [
      "節點是原創程序式位置，不是實際資料",
      "使用 v4 公開 RenderManager；升級須驗證此適配層",
    ],
    fallback: "固定網絡海報與停止動畫控制。",
    locked: [
      "Use real tsParticles particles and the links plugin.",
      "Disable autoPlay and drive RenderManager without scheduling RAF.",
      "Keep the bounded count and destroy the container.",
    ],
    dependencies: ["@tsparticles/engine", "@tsparticles/slim"],
    video: "adapter-required",
    visual: {
      background: "#173f49",
      foreground: "#e8ead3",
      accent: "#d9c68e",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-176",
    title: "彩紙系統・分批拋射",
    englishTitle: "tsParticles Confetti Trajectories",
    summary: "150 個方形粒子依明確時間函數分批拋出，點選可更改發射中心。",
    primary: "tsparticles",
    capabilities: ["particle-shapes", "burst-trajectories"],
    module: "physics-particles",
    variant: "confetti",
    renderer: "Canvas 2D",
    interaction: ["pointer", "touch", "keyboard", "timeline"],
    direction: "暖色活動識別",
    rationale: "四色彩紙搭配米色底，保留清楚形狀而非模糊光點。",
    why: "tsParticles 管理形狀、顏色、透明度與繪製；解析式拋射適配器讓時間可尋址。",
    uses: ["完成狀態回饋", "可調活動視覺"],
    nonUses: ["需要碰撞的物理彩紙", "使用者已啟用減少動態時持續播放"],
    instructions: "點選改變發射中心；方向鍵提供鍵盤替代操作。",
    limitations: [
      "軌跡為解析式拋射，不是碰撞模擬",
      "互動中心狀態需固定後才能做確定性影片",
    ],
    fallback: "固定彩紙分布海報。",
    locked: [
      "Use actual tsParticles square particles, paint and rotation.",
      "Keep the launch state explicit and all trajectories tied to host time.",
      "Do not enable independent container playback.",
    ],
    dependencies: ["@tsparticles/engine", "@tsparticles/slim"],
    video: "adapter-required",
    visual: {
      background: "#faf0da",
      foreground: "#573c58",
      accent: "#ce5e68",
      font: "Arial, sans-serif",
    },
  }),
  define({
    id: "SA-177",
    title: "流線筆記・種子噪聲",
    englishTitle: "p5 Seeded Flow Field",
    summary: "85 條流線依同一噪聲種子積分，在每個時間點重建完整畫面。",
    primary: "p5js",
    capabilities: ["seeded-noise", "flow-lines"],
    module: "generative-p5",
    variant: "flow",
    renderer: "Canvas 2D",
    interaction: ["timeline"],
    direction: "植物標本與地形筆記",
    rationale: "紙色底、細線與少量赭色重點讓生成規律保持可讀。",
    why: "p5 的 noiseSeed、繪圖狀態與 instance mode 適合可重現的生成式草圖。",
    uses: ["生成式視覺探索", "有機流線圖形"],
    nonUses: ["真實流體模擬", "具資料語意的流向地圖"],
    instructions: "拖曳時間軸，觀察整個場而非累積筆跡的變化。",
    limitations: [
      "合成噪聲場，並非地理或流體資料",
      "未保證不同 p5 版本的噪聲結果一致",
      "p5 2.3.4 使用獨立暫存頁面作用域；關閉案例即銷毀作用域",
    ],
    fallback: "固定時間生成的流線海報。",
    locked: [
      "Use p5 instance mode with noiseSeed(42).",
      "Use noLoop and externally requested redraw.",
      "Recompute each frame from explicit time and remove the p5 instance.",
    ],
    dependencies: ["p5"],
    video: "frame-driven",
  }),
  define({
    id: "SA-178",
    title: "諧波花園・數學生長",
    englishTitle: "p5 Harmonic Botanical Grid",
    summary: "十二組不同諧波參數的極座標曲線形成持續變化的數學圖版。",
    primary: "p5js",
    capabilities: ["polar-curves", "parametric-drawing"],
    module: "generative-p5",
    variant: "harmonics",
    renderer: "Canvas 2D",
    interaction: ["timeline"],
    direction: "數學植物圖鑑",
    rationale: "規律版面與線性花形讓參數差異可直接比較。",
    why: "p5 的頂點繪圖與數學函數可快速建立多組參數式曲線，無須將簡單向量圖升級為 3D。",
    uses: ["生成式圖形研究", "數學美學圖版"],
    nonUses: [
      "需要逐物件選取的向量編輯器",
      "可用單張 SVG 完成且不需生成變化的標誌",
    ],
    instructions: "比較不同列的花瓣數與變形節奏，或定位時間固定構圖。",
    limitations: [
      "花形為數學曲線，不是生物生長模型",
      "Canvas 內容沒有逐曲線語意節點",
      "p5 2.3.4 使用獨立暫存頁面作用域釋放全域包裝函式",
    ],
    fallback: "使用完整圖版的靜態影像。",
    locked: [
      "Use p5 vertex drawing for true parametric curves.",
      "Keep the twelve distinct parameter sets.",
      "Use host time, noLoop, redraw and instance removal.",
    ],
    dependencies: ["p5"],
    video: "frame-driven",
    visual: {
      background: "#f2ddd5",
      foreground: "#702c3d",
      accent: "#aa613d",
      font: "Arial, sans-serif",
    },
  }),
];
