/** Created: 2026-10-04. Canonical case-specific visual tokens for the physical studies. */
export type Scene = {
  key: string;
  title: string;
  subtitle: string;
  background: string;
  ink: string;
  accent: string;
  glow: string;
  direction: string;
};
export const physicsElementScenes: Scene[] = [
  {
    key: "fire",
    title: "IGNITION / PLUME",
    subtitle: "THERMAL LIFT · TURBULENT CURLS",
    background: "#100d12",
    ink: "#fff0ce",
    accent: "#ff642e",
    glow: "#ffd16b",
    direction: "熔岩玻璃與高溫攝影",
  },
  {
    key: "smoke",
    title: "SMOKE / VORTEX",
    subtitle: "BUOYANCY · VORTEX STRETCH",
    background: "#182026",
    ink: "#e6e8e0",
    accent: "#aebdc1",
    glow: "#687e88",
    direction: "低彩度煙霧研究",
  },
  {
    key: "splash",
    title: "WATER / CROWN",
    subtitle: "IMPACT · SHEET BREAKUP · DROPLETS",
    background: "#092633",
    ink: "#e9fbff",
    accent: "#4ec7cf",
    glow: "#b8ffff",
    direction: "深海水晶高速攝影",
  },
  {
    key: "swell",
    title: "OCEAN / SWELL",
    subtitle: "PHASED WAVE GROUP · FOAM LINE",
    background: "#08232a",
    ink: "#e2f5e6",
    accent: "#71c7b6",
    glow: "#e7d89a",
    direction: "海岸地形與青綠色層",
  },
  {
    key: "wind",
    title: "WIND / STREAMLINES",
    subtitle: "ADVECTION · BOUNDARY LAYER",
    background: "#e9e7df",
    ink: "#223c42",
    accent: "#c84d34",
    glow: "#748d8c",
    direction: "瑞士科學圖解與風洞線條",
  },
  {
    key: "lightning",
    title: "LIGHTNING / FORK",
    subtitle: "FIELD BREAKDOWN · BRANCHING ARC",
    background: "#090d20",
    ink: "#ececff",
    accent: "#a38aff",
    glow: "#e5f7ff",
    direction: "深夜風暴與紫白高壓光",
  },
  {
    key: "rain",
    title: "RAIN / RUNOFF",
    subtitle: "GRAVITY · IMPACT · GLASS FILM",
    background: "#1a2631",
    ink: "#e3edf3",
    accent: "#72b6c8",
    glow: "#d5eef4",
    direction: "城市窗景與玻璃水痕",
  },
  {
    key: "snow",
    title: "SNOW / DRIFT",
    subtitle: "DRAG · VORTEX · ACCUMULATION",
    background: "#dce6e8",
    ink: "#263943",
    accent: "#7baab4",
    glow: "#ffffff",
    direction: "冬日霧面攝影與冰藍",
  },
  {
    key: "sandfall",
    title: "GRANULAR / HOURGLASS",
    subtitle: "PARTICLE CASCADE · ANGLE OF REPOSE",
    background: "#201914",
    ink: "#f5e4c4",
    accent: "#df9b4d",
    glow: "#ffcc7d",
    direction: "琥珀沙鐘與金屬工藝",
  },
  {
    key: "ferrofluid",
    title: "FERROFLUID / FIELD",
    subtitle: "MAGNETIC STRESS · SPIKE FORMATION",
    background: "#101519",
    ink: "#f0eee4",
    accent: "#d1b36b",
    glow: "#f3df9e",
    direction: "黑金流體材料特寫",
  },
  {
    key: "bubble",
    title: "BUBBLES / BUOYANCY",
    subtitle: "BUOYANT RISE · COALESCENCE · POP",
    background: "#102a37",
    ink: "#e8f8f6",
    accent: "#85d9ce",
    glow: "#d4fffd",
    direction: "水下鏡頭與虹彩薄膜",
  },
  {
    key: "lava",
    title: "LAVA / VISCOSITY",
    subtitle: "SHEAR · CRUST · INCANDESCENT CORE",
    background: "#19100d",
    ink: "#ffe8bf",
    accent: "#f06427",
    glow: "#ffc14b",
    direction: "火山地質與熾熱岩層",
  },
  {
    key: "cloth",
    title: "CLOTH / GUST",
    subtitle: "TRAVELLING WAVE · TENSION FIELD",
    background: "#efe8dc",
    ink: "#24333c",
    accent: "#be453c",
    glow: "#d9a27e",
    direction: "高級布料型錄與側逆光",
  },
  {
    key: "pendulum",
    title: "PENDULUM / COUPLED",
    subtitle: "ANGULAR MOMENTUM · PHASE TRANSFER",
    background: "#f0eee5",
    ink: "#20383b",
    accent: "#c15d3a",
    glow: "#dfad60",
    direction: "博物館力學儀器",
  },
  {
    key: "domino",
    title: "DOMINO / CASCADE",
    subtitle: "CONTACT IMPULSE · SEQUENTIAL TOPPLE",
    background: "#f1eee5",
    ink: "#292d31",
    accent: "#b94639",
    glow: "#dca16c",
    direction: "建築模型桌與陶土色塊",
  },
  {
    key: "debris",
    title: "DEBRIS / IMPACT",
    subtitle: "BURST · ROTATION · SETTLE",
    background: "#1c2021",
    ink: "#f2ebdf",
    accent: "#dc8856",
    glow: "#f3c080",
    direction: "電影級石材碎裂攝影",
  },
  {
    key: "billiards",
    title: "COLLISION / ELASTIC",
    subtitle: "MOMENTUM TRANSFER · REFLECTION",
    background: "#09251d",
    ink: "#edf2d7",
    accent: "#d9b15a",
    glow: "#92c68d",
    direction: "賽事轉播台與桌球綠呢",
  },
  {
    key: "membrane",
    title: "MEMBRANE / MODES",
    subtitle: "STANDING WAVES · EDGE CONSTRAINT",
    background: "#f4efe7",
    ink: "#28343c",
    accent: "#dc7556",
    glow: "#d8a9aa",
    direction: "材料實驗室與透明薄膜",
  },
  {
    key: "rope",
    title: "ROPE / TRAVELING WAVE",
    subtitle: "TENSION · REFLECTION · DAMPING",
    background: "#e7e4db",
    ink: "#293d42",
    accent: "#b86643",
    glow: "#8aa8a1",
    direction: "纖維近拍與暖灰工業色",
  },
  {
    key: "orbit",
    title: "ORBIT / N-BODY",
    subtitle: "GRAVITY WELL · ELLIPTIC TRAJECTORY",
    background: "#080d1b",
    ink: "#eaf0ff",
    accent: "#9ab9f4",
    glow: "#ffd995",
    direction: "天文台暗場與恆星色彩",
  },
  {
    key: "whirlpool",
    title: "WHIRLPOOL / VORTEX",
    subtitle: "ANGULAR MOMENTUM · SPIRAL INFLOW",
    background: "#071d2a",
    ink: "#e4f6f4",
    accent: "#39acc0",
    glow: "#c3fbef",
    direction: "深海漩渦與俯視水紋",
  },
  {
    key: "fountain",
    title: "FOUNTAIN / JETS",
    subtitle: "BALLISTIC ARCS · PHASED EMISSION",
    background: "#182a32",
    ink: "#ebf3eb",
    accent: "#8ccdc6",
    glow: "#f5edcc",
    direction: "庭園噴泉與石材水景",
  },
  {
    key: "shockwave",
    title: "SHOCKWAVE / PRESSURE",
    subtitle: "COMPRESSIVE FRONT · REFRACTION",
    background: "#ecebe6",
    ink: "#26353b",
    accent: "#d65f48",
    glow: "#9ca9a5",
    direction: "空氣動力學高速攝影",
  },
  {
    key: "magnetic",
    title: "MAGNET / FIELD LINES",
    subtitle: "DIPOLE FIELD · FILING ALIGNMENT",
    background: "#f0eee6",
    ink: "#24383b",
    accent: "#bd5140",
    glow: "#5e8a80",
    direction: "實驗室磁場觀測",
  },
  {
    key: "dust",
    title: "DUST DEVIL / CONVECTION",
    subtitle: "THERMAL COLUMN · ROTATING PARTICLES",
    background: "#dbcfb8",
    ink: "#3b3328",
    accent: "#a36135",
    glow: "#ebbd78",
    direction: "乾燥荒原與塵柱逆光",
  },
  {
    key: "paper",
    title: "PAPER / FLUTTER",
    subtitle: "LIFT · DRAG · DIVERGENT FOLDS",
    background: "#f1eee6",
    ink: "#29343a",
    accent: "#c76447",
    glow: "#d9a986",
    direction: "紙藝工作室與暖白檯面",
  },
  {
    key: "buoyancy",
    title: "BUOYANCY / FLOAT",
    subtitle: "DISPLACEMENT · RESTORING FORCE",
    background: "#dfe8e2",
    ink: "#253c39",
    accent: "#bd6948",
    glow: "#88b8a7",
    direction: "產品靜物與水面折射",
  },
  {
    key: "crystal",
    title: "CRYSTAL / GROWTH",
    subtitle: "BRANCHED DEPOSITION · FACET LIGHT",
    background: "#141d2a",
    ink: "#e8f2f5",
    accent: "#76bdd0",
    glow: "#d9fbff",
    direction: "晶體標本與冷色切面光",
  },
  {
    key: "avalanche",
    title: "AVALANCHE / GRANULAR",
    subtitle: "SLOPE FAILURE · CASCADING FRONT",
    background: "#e3e8e7",
    ink: "#26383d",
    accent: "#658e9a",
    glow: "#ffffff",
    direction: "雪崩觀測與山體切面",
  },
  {
    key: "plasma",
    title: "PLASMA / SOLAR FLARE",
    subtitle: "MAGNETIC LOOP · EJECTA · CORONA",
    background: "#0c111d",
    ink: "#f9ebcb",
    accent: "#ff7544",
    glow: "#ffd16d",
    direction: "太陽日珥與日冕觀測",
  },
];
